### ISSUE TITLE
Create new crates.io Release

### ISSUE THREAD

**Issue by landonxjames** [amzn/ion-schema-rust#75]
The last release on crates.io is 4 months old and there have been several features implemented since then. Please push a new release to crates.io with the latest updates.

**Comment by desaikd** [comment]
Thanks for reaching out! We will work on adding a new release of `ion-schema-rust`.

**Comment by desaikd** [comment]
`ion-schema` new version [0.2.0](https://crates.io/crates/ion-schema) is available now.
